//: Playground - noun: a place where people can play

import UIKit

//Project Euler Problem 2
//Even Fibonacci numbers

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func fibonacci(maxNumber: Int) -> Int {

    var values: [Int] = []
    var tempArr = [1]

    var evenSum = 0
    var count = 1

    repeat {
        tempArr.append(count)

        let termTwo = tempArr[tempArr.count - 2]
        let termOne = tempArr[tempArr.count - 1]

        count = termTwo + termOne

    } while count <= maxNumber

    values = tempArr

    for value in values {
        if value % 2 == 0 {
            evenSum += value
        }
    }

    return evenSum
}

fibonacci(4000000)

